/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    disciplines: Discipline;
    industries: Industry;
    clients: Client;
    agencies: Agency;
    tags: Tag;
    media: Media;
    menus: Menu;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    disciplines: DisciplinesSelect<false> | DisciplinesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    agencies: AgenciesSelect<false> | AgenciesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    appearance: Appearance;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    appearance: AppearanceSelect<false> | AppearanceSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Shown below the hero, alongside the project title
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Small preview image used in the treemap
   */
  thumbnail?: (number | null) | Media;
  /**
   * The opening image or video. Video cover images also represent the project in transitions.
   */
  hero: {
    type: 'image' | 'video';
    image?: (number | null) | Media;
    /**
     * Paste a normal Vimeo share URL
     */
    videoURL?: string | null;
    /**
     * Shown before playback and used during the treemap transition
     */
    videoCover?: (number | null) | Media;
    /**
     * Visitors can switch a cropped video to contain mode from the hero.
     */
    videoFit?: ('cover' | 'contain') | null;
    /**
     * Starts automatically when the video enters the page. Autoplay is always muted.
     */
    autoplay?: boolean | null;
    loop?: boolean | null;
    muted?: boolean | null;
    controls?: boolean | null;
  };
  /**
   * Add images, videos and text in the order they should appear below the introduction
   */
  story?:
    | (
        | {
            image: number | Media;
            caption?: string | null;
            /**
             * Auto pairs adjacent portrait images. Choose a single layout to keep this image separate.
             */
            presentation: 'auto' | 'center' | 'full';
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * Paste a normal Vimeo share URL
             */
            url: string;
            /**
             * Recommended; also determines whether the video uses portrait or landscape sizing
             */
            poster?: (number | null) | Media;
            caption?: string | null;
            /**
             * Starts automatically when the video enters the page. Autoplay is always muted.
             */
            autoplay?: boolean | null;
            loop?: boolean | null;
            muted?: boolean | null;
            controls?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Uses larger type and quotation marks
             */
            quote?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
      )[]
    | null;
  slug: string;
  /**
   * Short description for meta tags and previews
   */
  excerpt?: string | null;
  client?: (number | null) | Client;
  /**
   * Studio or agency through which the project was commissioned
   */
  agency?: (number | null) | Agency;
  discipline: number | Discipline;
  /**
   * Client industries; used for portfolio filtering and menu links
   */
  industries?: (number | Industry)[] | null;
  /**
   * Higher values appear larger in the treemap (default: 100)
   */
  priority?: number | null;
  /**
   * Reusable terms describing the project
   */
  tags?: (number | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload files here. public/media is managed storage and files should not be copied into it manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  title: string;
  slug: string;
  /**
   * Optional client website, including https://
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Studios or agencies through which projects were commissioned.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies".
 */
export interface Agency {
  id: number;
  title: string;
  slug: string;
  /**
   * Optional agency website, including https://
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines".
 */
export interface Discipline {
  id: number;
  title: string;
  slug: string;
  /**
   * Colour used for this discipline in the treemap and project navigation.
   */
  color?: string | null;
  /**
   * Optional parent discipline for hierarchical organization
   */
  parent?: (number | null) | Discipline;
  /**
   * Higher values appear larger in the treemap (default: 100)
   */
  priority?: number | null;
  /**
   * Thumbnail image for the discipline
   */
  thumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  slug: string;
  /**
   * Colour assigned to this industry for menus and future visual grouping.
   */
  color?: string | null;
  /**
   * Optional parent industry for hierarchical organisation
   */
  parent?: (number | null) | Industry;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable project tags.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  title: string;
  slug: string;
  items?:
    | {
        /**
         * This title is the menu label, including for the Project guide destination.
         */
        title: string;
        type: 'internal' | 'external' | 'group';
        internalDestination?: ('content' | 'projects') | null;
        internalLink?:
          | ({
              relationTo: 'disciplines';
              value: number | Discipline;
            } | null)
          | ({
              relationTo: 'projects';
              value: number | Project;
            } | null)
          | ({
              relationTo: 'industries';
              value: number | Industry;
            } | null)
          | ({
              relationTo: 'clients';
              value: number | Client;
            } | null)
          | ({
              relationTo: 'agencies';
              value: number | Agency;
            } | null)
          | ({
              relationTo: 'tags';
              value: number | Tag;
            } | null);
        externalLink?: string | null;
        openInNewTab?: boolean | null;
        subItems?:
          | {
              /**
               * This title is the menu label, including for the Project guide destination.
               */
              title: string;
              type: 'internal' | 'external';
              internalDestination?: ('content' | 'projects') | null;
              internalLink?:
                | ({
                    relationTo: 'disciplines';
                    value: number | Discipline;
                  } | null)
                | ({
                    relationTo: 'projects';
                    value: number | Project;
                  } | null)
                | ({
                    relationTo: 'industries';
                    value: number | Industry;
                  } | null)
                | ({
                    relationTo: 'clients';
                    value: number | Client;
                  } | null)
                | ({
                    relationTo: 'agencies';
                    value: number | Agency;
                  } | null)
                | ({
                    relationTo: 'tags';
                    value: number | Tag;
                  } | null);
              externalLink?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'disciplines';
        value: number | Discipline;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'agencies';
        value: number | Agency;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  thumbnail?: T;
  hero?:
    | T
    | {
        type?: T;
        image?: T;
        videoURL?: T;
        videoCover?: T;
        videoFit?: T;
        autoplay?: T;
        loop?: T;
        muted?: T;
        controls?: T;
      };
  story?:
    | T
    | {
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              presentation?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              url?: T;
              poster?: T;
              caption?: T;
              autoplay?: T;
              loop?: T;
              muted?: T;
              controls?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              quote?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  excerpt?: T;
  client?: T;
  agency?: T;
  discipline?: T;
  industries?: T;
  priority?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines_select".
 */
export interface DisciplinesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  color?: T;
  parent?: T;
  priority?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  color?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agencies_select".
 */
export interface AgenciesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  items?:
    | T
    | {
        title?: T;
        type?: T;
        internalDestination?: T;
        internalLink?: T;
        externalLink?: T;
        openInNewTab?: T;
        subItems?:
          | T
          | {
              title?: T;
              type?: T;
              internalDestination?: T;
              internalLink?: T;
              externalLink?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteTitle: string;
  metaDescription?: string | null;
  /**
   * Title for the root level displayed in breadcrumb
   */
  rootDisciplineTitle?: string | null;
  /**
   * URL slug for the root level (use lowercase letters, no spaces or special characters)
   */
  rootDisciplineSlug?: string | null;
  /**
   * Used in the breadcrumb for the project relationship diagram.
   */
  projectGuideTitle: string;
  /**
   * URL segment for the project guide, without a leading slash.
   */
  projectsOverviewSlug: string;
  /**
   * Shown in the light grey area above the diagram.
   */
  projectGuideInstruction: string;
  /**
   * Logo shown at the root of the portfolio
   */
  rootLogo?: (number | null) | Media;
  /**
   * Logo shown below the root; clicking it moves up one level
   */
  upLogo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance".
 */
export interface Appearance {
  id: number;
  /**
   * Used for links, navigation logos and Project Map VIEW buttons.
   */
  keyColor: string;
  /**
   * Used by the main menu and the project guide instruction bar.
   */
  menuBackgroundColor: string;
  projectTitle: {
    placement: 'below' | 'overlay';
    fontSize?: number | null;
    mobileFontSize?: number | null;
    dimColor?: string | null;
    dimIntensity?: number | null;
  };
  storyText: {
    /**
     * Used on wider screens; text remains full width on mobile.
     */
    width: number;
    fontSize: number;
    quoteFontSize: number;
    textColor: string;
  };
  projectDescription: {
    /**
     * Enter a CSS font family name, e.g. October Condensed.
     */
    fontFamily: string;
    fontSize: number;
    textColor: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  metaDescription?: T;
  rootDisciplineTitle?: T;
  rootDisciplineSlug?: T;
  projectGuideTitle?: T;
  projectsOverviewSlug?: T;
  projectGuideInstruction?: T;
  rootLogo?: T;
  upLogo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance_select".
 */
export interface AppearanceSelect<T extends boolean = true> {
  keyColor?: T;
  menuBackgroundColor?: T;
  projectTitle?:
    | T
    | {
        placement?: T;
        fontSize?: T;
        mobileFontSize?: T;
        dimColor?: T;
        dimIntensity?: T;
      };
  storyText?:
    | T
    | {
        width?: T;
        fontSize?: T;
        quoteFontSize?: T;
        textColor?: T;
      };
  projectDescription?:
    | T
    | {
        fontFamily?: T;
        fontSize?: T;
        textColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}